[Errno 2] No such file or directory: '/tmp/tmpzi7p5ri0'
[Errno 2] No such file or directory: '/tmp/tmpigglwp0d'
[Errno 2] No such file or directory: '/tmp/tmpy_j0of11'
[Errno 2] No such file or directory: '/tmp/tmp0y1vwvti'
[Errno 2] No such file or directory: '/tmp/tmpun9abug2'
[Errno 2] No such file or directory: '/tmp/tmpo8996oro'
2022-02-17 09:56:26.235 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:56:26.234990
2022-02-17 09:56:26.235 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:56:26.235046
2022-02-17 09:56:26.235 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('0142ecda-8879-41af-8fd2-a57e26c87730')
2022-02-17 09:56:26.235 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('a79cbc14-b9d4-42bd-a5dd-73ea6ea31334')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/auto_info_worker.py", line 21, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/auto_info_worker.py", line 21, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2022-02-17 09:56:27.427 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:56:27.427423
2022-02-17 09:56:27.427 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:56:27.427471
2022-02-17 09:56:27.427 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('26de650e-85fb-428e-8983-daf64f1a7533')
2022-02-17 09:56:27.427 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('9f007b91-93b2-4182-a89d-577dccbdb6e6')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/auto_info_worker.py", line 21, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/auto_info_worker.py", line 21, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2022-02-17 09:56:29.624 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:56:29.624062
2022-02-17 09:56:29.624 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:56:29.624060
2022-02-17 09:56:29.631 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('ff7d3744-33e5-4973-9886-0ca141d5cad5')
2022-02-17 09:56:29.631 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('99e96fa0-145c-412b-a54b-cd8883e9115c')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/auto_info_worker.py", line 21, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/auto_info_worker.py", line 21, in <module>
    connection = pika.BlockingConnection(pika.ConnectionParameters(
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2022-02-17 09:57:55.140 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:57:55.140166
2022-02-17 09:57:55.140 | INFO     | __main__:<module>:17 - [INIT] Cтарт 2022-02-17 09:57:55.140152
2022-02-17 09:57:55.140 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('5de77bdf-4156-4908-8d56-de543903b016')
2022-02-17 09:57:55.140 | INFO     | __main__:<module>:20 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('60f5edd2-d3da-4b77-9e5b-ae0c5c3419ed')
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/gibdd_parser/venv/lib/python3.8/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
2022-02-17 09:58:03.640 | INFO     | __main__:<module>:107 - [Server] Awaiting RPC requests
2022-02-17 09:58:05.222 | INFO     | __main__:<module>:107 - [Server] Awaiting RPC requests
2022-02-17 09:59:28.828 | INFO     | __main__:on_request:76 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "898cc62b-d87c-4882-a55d-87d4193a813a"})
2022-02-17 09:59:28.828 | INFO     | __main__:on_request:90 -  [OR] data({'vin_code': 'XWKFB227390094336', 'method': 'road_accident_history', 'uuid': '898cc62b-d87c-4882-a55d-87d4193a813a'})
2022-02-17 09:59:28.828 | INFO     | parsers:_send_field_waits:165 - Отправка кода в input_field 
2022-02-17 09:59:28.837 | INFO     | __main__:on_request:76 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "registration_history", "uuid": "e202d294-b64a-41a5-8b3f-0b8dfdd8bde6"})
2022-02-17 09:59:28.837 | INFO     | __main__:on_request:90 -  [OR] data({'vin_code': 'XWKFB227390094336', 'method': 'registration_history', 'uuid': 'e202d294-b64a-41a5-8b3f-0b8dfdd8bde6'})
2022-02-17 09:59:28.837 | INFO     | parsers:_send_field_waits:165 - Отправка кода в input_field 
2022-02-17 09:59:28.868 | INFO     | parsers:_send_field_waits:174 - Ввод VIN кода: XWKFB227390094336
2022-02-17 09:59:28.868 | INFO     | parsers:_get_road_accident_history:481 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 09:59:28.886 | INFO     | parsers:_send_field_waits:174 - Ввод VIN кода: XWKFB227390094336
2022-02-17 09:59:28.887 | INFO     | parsers:_get_registration_history_webdriver_wait:408 - [REGISTRATION]Старт получения данных истории регистрации
2022-02-17 09:59:29.300 | INFO     | parsers:_get_registration_history_webdriver_wait:432 - [REGISTRATION-BUTTON] Нажата кнопка поиска
2022-02-17 09:59:29.445 | INFO     | parsers:_get_road_accident_history:499 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 09:59:31.027 | INFO     | parsers:_get_registration_history_webdriver_wait:443 - [REGISTRATION-DATA] Данные прогрузились
2022-02-17 09:59:31.030 | INFO     | parsers:_get_registration_history_webdriver_wait:452 - [REGISTRATION-PARSING] Найден блок результатов
2022-02-17 09:59:31.282 | INFO     | parsers:_get_registration_history_webdriver_wait:457 - [REGISTRATION-PARSING] Найдены результаты unparsed_data='Марка и(или) модель: \nКIА SРЕСТRА (FВ2273)\nГод выпуска: \n2008\nИдентификационный номер (VIN): \nХWКFВ227390094336\nНомер шасси (рамы): \n-\nНомер кузова (кабины): \nХWКFВ227390094336\nЦвет кузова (кабины): \nЧЕРНЫЙ ЖЕМЧУГ\nНомер двигателя: \n187913\nРабочий объем (см³): \n1594.0\nМощность (кВт/л.с.): \n74.63/101.5\nТип транспортного средства: \nЛегковые автомобили седан\nПериоды владения транспортным средством\nc 22.10.2008 по 07.11.2014: Физическое лицо\nc 07.11.2014 по 02.09.2015: Физическое лицо\nc 02.09.2015 по настоящее время: Физическое лицо\nПоследняя операция - изменение собственника (владельца)'
2022-02-17 09:59:31.282 | INFO     | parsers:_change_data_output_format:277 - [REGISTRATION-DATA]: ['Периоды', 'владения', 'транспортным', 'средством']
2022-02-17 09:59:31.283 | INFO     | parsers:_change_data_output_format:277 - [REGISTRATION-DATA]: ['c', '22.10.2008', 'по', '07.11.2014:', 'Физическое', 'лицо']
2022-02-17 09:59:31.283 | INFO     | parsers:_change_data_output_format:277 - [REGISTRATION-DATA]: ['c', '07.11.2014', 'по', '02.09.2015:', 'Физическое', 'лицо']
2022-02-17 09:59:31.283 | INFO     | parsers:_change_data_output_format:277 - [REGISTRATION-DATA]: ['c', '02.09.2015', 'по', 'настоящее', 'время:', 'Физическое', 'лицо']
2022-02-17 09:59:31.283 | INFO     | parsers:_change_data_output_format:277 - [REGISTRATION-DATA]: ['Последняя', 'операция', '-', 'изменение', 'собственника', '(владельца)']
2022-02-17 09:59:31.283 | INFO     | parsers:_change_data_output_format:291 - [DATA]: {'vehicle_brand_or_model': 'КIА SРЕСТRА (FВ2273)', 'model_product_year': '2008', 'vin_code': 'ХWКFВ227390094336', 'chasis_number': '-', 'body_number': 'ХWКFВ227390094336', 'color': 'ЧЕРНЫЙ ЖЕМЧУГ', 'engine_number': '187913', 'working_volume': '1594.0', 'power': '74.63/101.5', 'vehicle_type': 'Легковые автомобили седан'}
2022-02-17 09:59:31.284 | INFO     | __main__:on_request:99 -  [Server] response({'result': 'Success', 'data': {'registration_history': {'vehicle_brand_or_model': 'КIА SРЕСТRА (FВ2273)', 'model_product_year': '2008', 'vin_code': 'ХWКFВ227390094336', 'chasis_number': '-', 'body_number': 'ХWКFВ227390094336', 'color': 'ЧЕРНЫЙ ЖЕМЧУГ', 'engine_number': '187913', 'working_volume': '1594.0', 'power': '74.63/101.5', 'vehicle_type': 'Легковые автомобили седан', 'periods_of_vehicle_ownership': ['c 22.10.2008 по 07.11.2014: Физическое лицо', 'c 07.11.2014 по 02.09.2015: Физическое лицо', 'c 02.09.2015 по настоящее время: Физическое лицо'], 'last_operation': 'Последняя операция - изменение собственника (владельца)'}}, 'uuid': 'e202d294-b64a-41a5-8b3f-0b8dfdd8bde6'})
2022-02-17 09:59:31.634 | INFO     | __main__:on_request:101 -  [Server] cleaned page!
2022-02-17 09:59:41.140 | INFO     | parsers:_get_road_accident_history:508 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 09:59:41.733 | INFO     | parsers:_get_road_accident_history:528 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 09:59:44.801 | INFO     | parsers:_save_road_accident_image_1c:201 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 09:59:44.801 | INFO     | parsers:_save_road_accident_image_1c:204 - [ACCIDENT-I] Отправка изображения в сервис http://192.168.0.7/filesprogr/index.php?operation=write&extension=png&author=parserGIBDD&typedoc=2&filename=2022-02-1709:59:44.801275.jpg
2022-02-17 09:59:44.985 | INFO     | parsers:_save_road_accident_image_1c:214 - [ACCIDENT-I] UUID изображения на сервисе a53404f8-3303-4b2e-9be3-1b2f036a3918
2022-02-17 09:59:45.078 | INFO     | parsers:_save_road_accident_image_1c:201 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 09:59:45.078 | INFO     | parsers:_save_road_accident_image_1c:204 - [ACCIDENT-I] Отправка изображения в сервис http://192.168.0.7/filesprogr/index.php?operation=write&extension=png&author=parserGIBDD&typedoc=2&filename=2022-02-1709:59:45.078822.jpg
2022-02-17 09:59:45.145 | INFO     | parsers:_save_road_accident_image_1c:214 - [ACCIDENT-I] UUID изображения на сервисе b9f2342d-270c-4dda-adf6-1b3499e4a8d3
2022-02-17 09:59:45.145 | INFO     | __main__:on_request:99 -  [Server] response({'result': 'Success', 'data': {'road_accident_history': {'dtp_list': [{'accident_id': '030059033', 'date': '08.08.2018 07:45', 'incedent_type': 'Столкновение', 'region': 'Краснодарский край', 'incedent_place': 'Краснодарский край, Анапский район, Анапа', 'venhicle_model': 'KIA(Spectra)', 'model_product_year': '2008', 'opf': 'ФИЗИЧЕСКИЕ ЛИЦА', 'tc_number': '2/2', 'damage_desc': ['Переднее правое крыло'], 'images': 'a53404f8-3303-4b2e-9be3-1b2f036a3918'}, {'accident_id': '610004065', 'date': '19.02.2015 10:05', 'incedent_type': 'Столкновение', 'region': 'Рязанская область', 'incedent_place': 'Рязанская область, Рязань, Советский', 'venhicle_model': 'KIA(Spectra)', 'model_product_year': 'нет данных', 'opf': 'ФИЗИЧЕСКИЕ ЛИЦА', 'tc_number': '1/2', 'damage_desc': [], 'images': 'b9f2342d-270c-4dda-adf6-1b3499e4a8d3'}]}}, 'uuid': '898cc62b-d87c-4882-a55d-87d4193a813a'})
2022-02-17 09:59:45.505 | INFO     | __main__:on_request:101 -  [Server] cleaned page!
2022-02-17 10:11:18.298 | INFO     | __main__:exit_gracefully:39 - Kill
2022-02-17 10:11:18.298 | INFO     | __main__:exit_gracefully:39 - Kill
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 47, in <module>
    from utils.loggers import parser_logger
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/loggers.py", line 8, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 47, in <module>
    from utils.loggers import parser_logger
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/loggers.py", line 8, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 47, in <module>
    from utils.loggers import parser_logger
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/loggers.py", line 8, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 47, in <module>
    from utils.loggers import parser_logger
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/loggers.py", line 8, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 47, in <module>
    from utils.loggers import parser_logger
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/loggers.py", line 8, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 47, in <module>
    from utils.loggers import parser_logger
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/loggers.py", line 8, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 9, in <module>
    from parsers import BotParser
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 48, in <module>
    from utils.work_with_proxy import read_proxy_json
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/work_with_proxy.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
2022-02-17 11:01:40.981 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:01:40.981524
2022-02-17 11:01:40.981 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:01:40.981564
2022-02-17 11:01:40.981 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('cb49a137-a2f4-4087-982b-fd1ea6934cf6')
2022-02-17 11:01:40.981 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('5389cfa1-7bf9-43d8-a752-f003361f48e3')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 98, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/firefox_addons/ublock_origin.xpi'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 98, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/firefox_addons/ublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7fbd28aa61f0>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 760, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7f22c85721f0>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 760, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:01:42.388 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:01:42.388927
2022-02-17 11:01:42.388 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:01:42.388293
2022-02-17 11:01:42.393 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('4363efed-b791-4491-a1ae-19f6ecbbd2af')
2022-02-17 11:01:42.393 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('31b1e534-feca-4cf7-a7d0-8a6c5fc48121')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 98, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/firefox_addons/ublock_origin.xpi'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 98, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/firefox_addons/ublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7f0cd66f81f0>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 760, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7fbf2a3b11f0>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 760, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:01:44.781 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:01:44.781854
2022-02-17 11:01:44.782 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:01:44.782279
2022-02-17 11:01:44.790 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('5c793519-e7ac-4cd0-b335-f24ac6dce5da')
2022-02-17 11:01:44.790 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('efec779c-1150-480d-a679-280435b27583')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 98, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/firefox_addons/ublock_origin.xpi'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 98, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parser-gibdd-docker/rabbitMQ/firefox_addons/ublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7f7b1107b1f0>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 760, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7f7a2e0101f0>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 760, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:04:01.813 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:04:01.813813
2022-02-17 11:04:01.814 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('5afaafc9-6f2b-4d3c-b2be-918e7c2ee6bc')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addons/firefox_addons/ublock_origin.xpi'
2022-02-17 11:04:01.820 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:04:01.820496
2022-02-17 11:04:01.820 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('4b805498-4c81-420b-b2c8-0d4274faf2e0')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addons/firefox_addons/ublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7f33f7ce9550>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7f027ae46550>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:04:03.204 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:04:03.204601
2022-02-17 11:04:03.204 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('61ca32c1-30d0-481c-80b9-33ce83642b32')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addons/firefox_addons/ublock_origin.xpi'
2022-02-17 11:04:03.218 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:04:03.218764
2022-02-17 11:04:03.219 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('7ec77347-425a-47f3-bc0b-1b35cfac5bc3')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addons/firefox_addons/ublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7f7f6b99e430>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7f0e77a8a430>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:05:15.206 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:15.206535
2022-02-17 11:05:15.206 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:15.206573
2022-02-17 11:05:15.207 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('82977279-887e-4001-9dae-065b1e80e57d')
2022-02-17 11:05:15.208 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('d61f76f1-99ba-4575-85a0-1f1fb02ebb4b')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addonsublock_origin.xpi'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addonsublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7f629a87a550>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7f7349ad7550>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:05:16.561 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:16.561615
2022-02-17 11:05:16.561 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:16.561602
2022-02-17 11:05:16.569 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('02bcee42-209a-4ec9-b446-faa5acbc677f')
2022-02-17 11:05:16.569 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('cf9302cb-7f17-4d29-b45c-7bbbd28964ee')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addonsublock_origin.xpi'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addonsublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7f23db544430>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7f087c0be430>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:05:18.921 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:18.921683
2022-02-17 11:05:18.921 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:18.921677
2022-02-17 11:05:18.921 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('ada6dd28-6fcc-433f-b38f-a19dd41ecd34')
2022-02-17 11:05:18.921 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('173559cc-77a0-4533-a43d-1f938423008c')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addonsublock_origin.xpi'
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 99, in __init__
    profile.add_extension(extension=extensions_path + 'ublock_origin.xpi')
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 92, in add_extension
    self._install_extension(extension)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 218, in _install_extension
    compressed_file = zipfile.ZipFile(addon, 'r')
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/utils/firefox_addonsublock_origin.xpi'
Exception ignored in: <function BotParser.__del__ at 0x7fa7fbae6430>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
Exception ignored in: <function BotParser.__del__ at 0x7fcda4951430>
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 761, in __del__
    self.driver.quit()
AttributeError: 'BotParser' object has no attribute 'driver'
2022-02-17 11:05:58.862 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:58.862517
2022-02-17 11:05:58.862 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('70a5eff9-4be1-4bd6-b732-de1ad1896cf9')
2022-02-17 11:05:58.863 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:05:58.863340
2022-02-17 11:05:58.863 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('73c1151d-e73d-430a-a6e3-88a353aef64b')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 118, in __init__
    self.driver.get(URL)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//xn--90adear.xn--p1ai/check/auto&c=UTF-8&d=%D0%9C%D1%8B%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D0%BC%20%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F%20%D0%BA%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D1%83%20xn--90adear.xn--p1ai.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:510:5
checkReadyState@chrome://remote/content/marionette/navigate.js:64:24
onNavigation@chrome://remote/content/marionette/navigate.js:312:39
emit@resource://gre/modules/EventEmitter.jsm:160:20
receiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:44:25

Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 118, in __init__
    self.driver.get(URL)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//xn--90adear.xn--p1ai/check/auto&c=UTF-8&d=%D0%9C%D1%8B%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D0%BC%20%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F%20%D0%BA%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D1%83%20xn--90adear.xn--p1ai.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:510:5
checkReadyState@chrome://remote/content/marionette/navigate.js:64:24
onNavigation@chrome://remote/content/marionette/navigate.js:312:39
emit@resource://gre/modules/EventEmitter.jsm:160:20
receiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:44:25

2022-02-17 11:06:04.940 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:06:04.940421
2022-02-17 11:06:04.940 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('34649315-2180-4bcc-818f-f30276880038')
2022-02-17 11:06:05.212 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:06:05.212027
2022-02-17 11:06:05.212 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('faff0b08-f278-40c6-8b3b-1c2b35bf8342')
Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 118, in __init__
    self.driver.get(URL)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//xn--90adear.xn--p1ai/check/auto&c=UTF-8&d=%D0%9C%D1%8B%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D0%BC%20%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F%20%D0%BA%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D1%83%20xn--90adear.xn--p1ai.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:510:5
checkReadyState@chrome://remote/content/marionette/navigate.js:64:24
onNavigation@chrome://remote/content/marionette/navigate.js:312:39
emit@resource://gre/modules/EventEmitter.jsm:160:20
receiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:44:25

Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 24, in <module>
    parser = BotParser()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 118, in __init__
    self.driver.get(URL)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 436, in get
    self.execute(Command.GET, {'url': url})
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=dnsNotFound&u=https%3A//xn--90adear.xn--p1ai/check/auto&c=UTF-8&d=%D0%9C%D1%8B%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D0%BC%20%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%D1%82%D1%8C%D1%81%D1%8F%20%D0%BA%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D1%83%20xn--90adear.xn--p1ai.
Stacktrace:
WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:183:5
UnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:510:5
checkReadyState@chrome://remote/content/marionette/navigate.js:64:24
onNavigation@chrome://remote/content/marionette/navigate.js:312:39
emit@resource://gre/modules/EventEmitter.jsm:160:20
receiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:44:25

2022-02-17 11:06:11.008 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:06:11.008409
2022-02-17 11:06:11.008 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('4be35ed8-daa1-4d80-9c37-c09bb98169e3')
2022-02-17 11:06:11.283 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:06:11.283038
2022-02-17 11:06:11.283 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('cf6cd39d-caf3-4091-827b-5a14494e6043')
2022-02-17 11:56:37.817 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:56:37.817766
2022-02-17 11:56:37.817 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('f861414c-4ecb-4f62-9b7a-9da76dbc8bae')
2022-02-17 11:56:37.817 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 11:56:37.817972
2022-02-17 11:56:37.818 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('ecb973f6-21f6-46d0-a3d6-f95896696fb9')
2022-02-17 11:56:46.128 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('f861414c-4ecb-4f62-9b7a-9da76dbc8bae')
2022-02-17 11:56:47.367 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('ecb973f6-21f6-46d0-a3d6-f95896696fb9')
2022-02-17 12:05:30.060 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "96dac517-a17b-4d42-b42b-135c9b9a26a2"}) WORKER_UUID=UUID('f861414c-4ecb-4f62-9b7a-9da76dbc8bae')
2022-02-17 12:05:30.060 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "registration_history", "uuid": "a7ee949f-32f6-45fd-87b6-48854ad6954d"}) WORKER_UUID=UUID('ecb973f6-21f6-46d0-a3d6-f95896696fb9')
2022-02-17 12:05:30.061 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:05:30.061 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:05:30.103 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:05:30.103 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:05:30.103 | INFO     | parsers:_get_road_accident_history:474 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 12:05:30.103 | INFO     | parsers:_get_registration_history_webdriver_wait:401 - [REGISTRATION]Старт получения данных истории регистрации
2022-02-17 12:05:30.423 | INFO     | parsers:_get_registration_history_webdriver_wait:425 - [REGISTRATION-BUTTON] Нажата кнопка поиска
2022-02-17 12:05:30.633 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:05:30.972 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:31.153 | INFO     | parsers:_get_registration_history_webdriver_wait:436 - [REGISTRATION-DATA] Данные прогрузились
2022-02-17 12:05:31.156 | INFO     | parsers:_get_registration_history_webdriver_wait:445 - [REGISTRATION-PARSING] Найден блок результатов
2022-02-17 12:05:31.552 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 12:05:31.891 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:32.014 | INFO     | parsers:_get_registration_history_webdriver_wait:450 - [REGISTRATION-PARSING] Найдены результаты unparsed_data='Марка и(или) модель: \nКIА SРЕСТRА (FВ2273)\nГод выпуска: \n2008\nИдентификационный номер (VIN): \nХWКFВ227390094336\nНомер шасси (рамы): \n-\nНомер кузова (кабины): \nХWКFВ227390094336\nЦвет кузова (кабины): \nЧЕРНЫЙ ЖЕМЧУГ\nНомер двигателя: \n187913\nРабочий объем (см³): \n1594.0\nМощность (кВт/л.с.): \n74.63/101.5\nТип транспортного средства: \nЛегковые автомобили седан\nПериоды владения транспортным средством\nc 22.10.2008 по 07.11.2014: Физическое лицо\nc 07.11.2014 по 02.09.2015: Физическое лицо\nc 02.09.2015 по настоящее время: Физическое лицо\nПоследняя операция - изменение собственника (владельца)'
2022-02-17 12:05:32.015 | INFO     | parsers:_change_data_output_format:270 - [REGISTRATION-DATA]: ['Периоды', 'владения', 'транспортным', 'средством']
2022-02-17 12:05:32.015 | INFO     | parsers:_change_data_output_format:270 - [REGISTRATION-DATA]: ['c', '22.10.2008', 'по', '07.11.2014:', 'Физическое', 'лицо']
2022-02-17 12:05:32.015 | INFO     | parsers:_change_data_output_format:270 - [REGISTRATION-DATA]: ['c', '07.11.2014', 'по', '02.09.2015:', 'Физическое', 'лицо']
2022-02-17 12:05:32.015 | INFO     | parsers:_change_data_output_format:270 - [REGISTRATION-DATA]: ['c', '02.09.2015', 'по', 'настоящее', 'время:', 'Физическое', 'лицо']
2022-02-17 12:05:32.015 | INFO     | parsers:_change_data_output_format:270 - [REGISTRATION-DATA]: ['Последняя', 'операция', '-', 'изменение', 'собственника', '(владельца)']
2022-02-17 12:05:32.015 | INFO     | parsers:_change_data_output_format:284 - [DATA]: {'vehicle_brand_or_model': 'КIА SРЕСТRА (FВ2273)', 'model_product_year': '2008', 'vin_code': 'ХWКFВ227390094336', 'chasis_number': '-', 'body_number': 'ХWКFВ227390094336', 'color': 'ЧЕРНЫЙ ЖЕМЧУГ', 'engine_number': '187913', 'working_volume': '1594.0', 'power': '74.63/101.5', 'vehicle_type': 'Легковые автомобили седан'}
2022-02-17 12:05:32.016 | INFO     | __main__:on_request:95 -  [Server] response({'result': 'Success', 'data': {'registration_history': {'vehicle_brand_or_model': 'КIА SРЕСТRА (FВ2273)', 'model_product_year': '2008', 'vin_code': 'ХWКFВ227390094336', 'chasis_number': '-', 'body_number': 'ХWКFВ227390094336', 'color': 'ЧЕРНЫЙ ЖЕМЧУГ', 'engine_number': '187913', 'working_volume': '1594.0', 'power': '74.63/101.5', 'vehicle_type': 'Легковые автомобили седан', 'periods_of_vehicle_ownership': ['c 22.10.2008 по 07.11.2014: Физическое лицо', 'c 07.11.2014 по 02.09.2015: Физическое лицо', 'c 02.09.2015 по настоящее время: Физическое лицо'], 'last_operation': 'Последняя операция - изменение собственника (владельца)'}}, 'uuid': 'a7ee949f-32f6-45fd-87b6-48854ad6954d'}) WORKER_UUID=UUID('ecb973f6-21f6-46d0-a3d6-f95896696fb9')
2022-02-17 12:05:32.476 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 2
2022-02-17 12:05:32.806 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:33.258 | INFO     | __main__:on_request:97 -  [Server] cleaned page! WORKER_UUID=UUID('ecb973f6-21f6-46d0-a3d6-f95896696fb9')
2022-02-17 12:05:33.376 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 3
2022-02-17 12:05:33.724 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:34.299 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 4
2022-02-17 12:05:34.628 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:35.205 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 5
2022-02-17 12:05:35.551 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:36.120 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 6
2022-02-17 12:05:36.582 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:05:36.894 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:37.464 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 7
2022-02-17 12:05:37.780 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:38.409 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 8
2022-02-17 12:05:38.723 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:39.333 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 9
2022-02-17 12:05:39.646 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:40.215 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 10
2022-02-17 12:05:40.578 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:41.151 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 11
2022-02-17 12:05:41.463 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:42.076 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 12
2022-02-17 12:05:42.529 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:05:42.844 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:43.468 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 13
2022-02-17 12:05:43.785 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:44.363 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 14
2022-02-17 12:05:44.683 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:45.252 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 15
2022-02-17 12:05:45.563 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:46.130 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 16
2022-02-17 12:05:46.435 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:47.002 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 17
2022-02-17 12:05:47.315 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:47.891 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 18
2022-02-17 12:05:48.364 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:05:48.676 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:05:49.245 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 19
2022-02-17 12:05:52.098 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:05:52.099 | INFO     | __main__:on_request:95 -  [Server] response({'result': 'Fail', 'data': {'error': 'Parser error 2022-02-17 12:05:52.098911'}, 'uuid': '96dac517-a17b-4d42-b42b-135c9b9a26a2'}) WORKER_UUID=UUID('f861414c-4ecb-4f62-9b7a-9da76dbc8bae')
2022-02-17 12:05:53.349 | INFO     | __main__:on_request:97 -  [Server] cleaned page! WORKER_UUID=UUID('f861414c-4ecb-4f62-9b7a-9da76dbc8bae')
2022-02-17 12:11:12.718 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('f861414c-4ecb-4f62-9b7a-9da76dbc8bae')
2022-02-17 12:11:12.718 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('ecb973f6-21f6-46d0-a3d6-f95896696fb9')
2022-02-17 12:11:28.789 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:11:28.789340
2022-02-17 12:11:28.789 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:11:28.789360
2022-02-17 12:11:28.789 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('d9925a7e-3a55-4445-9e1f-4972d72ad2ca')
2022-02-17 12:11:28.789 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('da1ee45d-1719-4d23-bf93-d31481a66312')
2022-02-17 12:11:36.490 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('da1ee45d-1719-4d23-bf93-d31481a66312')
2022-02-17 12:11:36.926 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('d9925a7e-3a55-4445-9e1f-4972d72ad2ca')
2022-02-17 12:11:43.631 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "d32af286-31ac-42a0-8ed7-ebbfac421cfb"}) WORKER_UUID=UUID('da1ee45d-1719-4d23-bf93-d31481a66312')
2022-02-17 12:11:43.638 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:11:43.672 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:11:43.672 | INFO     | parsers:_get_road_accident_history:474 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 12:11:44.176 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:11:44.510 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:11:45.179 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 12:11:45.487 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:11:46.053 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 2
2022-02-17 12:11:46.355 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:11:46.964 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 3
2022-02-17 12:11:47.281 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:11:47.850 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 4
2022-02-17 12:11:59.139 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:11:59.732 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 5
2022-02-17 12:12:02.483 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:12:02.491 | ERROR    | __main__:parse:63 - Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 488, in _get_road_accident_history
    tracing_button = self.driver. \
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: запросить сведения о ДТП


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 51, in parse
    data_from_parser = parser.parse_data(vin_code, method)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 713, in parse_data
    data2 = self._get_road_accident_history()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 513, in _get_road_accident_history
    return_data = self._change_dtp_output(result)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 247, in _change_dtp_output
    local_dict['images'] = self._save_road_accident_image_1c(item)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 196, in _save_road_accident_image_1c
    url = FILES_1C % (filename, )
NameError: name 'FILES_1C' is not defined

2022-02-17 12:12:02.491 | INFO     | __main__:on_request:95 -  [Server] response({'result': 'Fail', 'data': {'error': 'Parser error 2022-02-17 12:12:02.491489'}, 'uuid': 'd32af286-31ac-42a0-8ed7-ebbfac421cfb'}) WORKER_UUID=UUID('da1ee45d-1719-4d23-bf93-d31481a66312')
2022-02-17 12:12:02.991 | INFO     | __main__:on_request:97 -  [Server] cleaned page! WORKER_UUID=UUID('da1ee45d-1719-4d23-bf93-d31481a66312')
2022-02-17 12:12:59.711 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "862c44a7-35bf-4585-ad13-30f296c653dc"}) WORKER_UUID=UUID('d9925a7e-3a55-4445-9e1f-4972d72ad2ca')
2022-02-17 12:12:59.712 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:12:59.751 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:12:59.751 | INFO     | parsers:_get_road_accident_history:474 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 12:13:00.252 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:13:11.450 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:12.081 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 12:13:14.844 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:13:14.845 | ERROR    | __main__:parse:63 - Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 488, in _get_road_accident_history
    tracing_button = self.driver. \
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: запросить сведения о ДТП


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/auto_info_worker.py", line 51, in parse
    data_from_parser = parser.parse_data(vin_code, method)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 713, in parse_data
    data2 = self._get_road_accident_history()
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 513, in _get_road_accident_history
    return_data = self._change_dtp_output(result)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 247, in _change_dtp_output
    local_dict['images'] = self._save_road_accident_image_1c(item)
  File "/home/kolchanovaa/Рабочий стол/parsers/parsers_gibdd_rabbitMQ/parsers.py", line 196, in _save_road_accident_image_1c
    url = FILES_1C % (filename, )
NameError: name 'FILES_1C' is not defined

2022-02-17 12:13:14.846 | INFO     | __main__:on_request:95 -  [Server] response({'result': 'Fail', 'data': {'error': 'Parser error 2022-02-17 12:13:14.845762'}, 'uuid': '862c44a7-35bf-4585-ad13-30f296c653dc'}) WORKER_UUID=UUID('d9925a7e-3a55-4445-9e1f-4972d72ad2ca')
2022-02-17 12:13:15.349 | INFO     | __main__:on_request:97 -  [Server] cleaned page! WORKER_UUID=UUID('d9925a7e-3a55-4445-9e1f-4972d72ad2ca')
2022-02-17 12:13:28.364 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('da1ee45d-1719-4d23-bf93-d31481a66312')
2022-02-17 12:13:28.364 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('d9925a7e-3a55-4445-9e1f-4972d72ad2ca')
2022-02-17 12:13:33.258 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:13:33.258158
2022-02-17 12:13:33.258 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('4c6e7cb6-3168-4cfb-a3d6-e68a0527d9fa')
2022-02-17 12:13:33.264 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:13:33.264299
2022-02-17 12:13:33.264 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('4f6d70d2-13e9-4f0c-8f95-863f7b677d34')
2022-02-17 12:13:39.836 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('4f6d70d2-13e9-4f0c-8f95-863f7b677d34')
2022-02-17 12:13:41.049 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('4c6e7cb6-3168-4cfb-a3d6-e68a0527d9fa')
2022-02-17 12:13:44.858 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "9fcbee18-c506-4b49-9af9-0ae9bd0fbd89"}) WORKER_UUID=UUID('4f6d70d2-13e9-4f0c-8f95-863f7b677d34')
2022-02-17 12:13:44.866 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:13:44.898 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:13:44.898 | INFO     | parsers:_get_road_accident_history:474 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 12:13:45.393 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:13:45.711 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:46.323 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 12:13:46.649 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:47.217 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 2
2022-02-17 12:13:47.552 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:48.131 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 3
2022-02-17 12:13:48.438 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:49.048 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 4
2022-02-17 12:13:49.355 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:49.921 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 5
2022-02-17 12:13:50.245 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:50.815 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 6
2022-02-17 12:13:51.295 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:13:51.613 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:52.192 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 7
2022-02-17 12:13:52.502 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:53.079 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 8
2022-02-17 12:13:53.374 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:53.945 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 9
2022-02-17 12:13:54.244 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:54.864 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 10
2022-02-17 12:13:55.197 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:55.810 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 11
2022-02-17 12:13:56.128 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:56.737 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 12
2022-02-17 12:13:57.192 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:13:57.506 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:13:58.075 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 13
2022-02-17 12:14:09.530 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:14:10.170 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 14
2022-02-17 12:14:12.942 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:14:12.942 | INFO     | parsers:_save_road_accident_image_1c:197 - [ACCIDENT-I] Отправка изображения в сервис http://192.168.0.7/filesprogr/index.php?operation=write&extension=png&author=parserGIBDD&typedoc=2&filename=2022-02-1712:14:12.942736.jpg
2022-02-17 12:14:13.031 | INFO     | parsers:_save_road_accident_image_1c:207 - [ACCIDENT-I] UUID изображения на сервисе a53404f8-3303-4b2e-9be3-1b2f036a3918
2022-02-17 12:14:13.126 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:14:13.126 | INFO     | parsers:_save_road_accident_image_1c:197 - [ACCIDENT-I] Отправка изображения в сервис http://192.168.0.7/filesprogr/index.php?operation=write&extension=png&author=parserGIBDD&typedoc=2&filename=2022-02-1712:14:13.126361.jpg
2022-02-17 12:14:13.193 | INFO     | parsers:_save_road_accident_image_1c:207 - [ACCIDENT-I] UUID изображения на сервисе b9f2342d-270c-4dda-adf6-1b3499e4a8d3
2022-02-17 12:14:13.194 | INFO     | __main__:on_request:95 -  [Server] response({'result': 'Success', 'data': {'road_accident_history': {'dtp_list': [{'accident_id': '030059033', 'date': '08.08.2018 07:45', 'incedent_type': 'Столкновение', 'region': 'Краснодарский край', 'incedent_place': 'Краснодарский край, Анапский район, Анапа', 'venhicle_model': 'KIA(Spectra)', 'model_product_year': '2008', 'opf': 'ФИЗИЧЕСКИЕ ЛИЦА', 'tc_number': '2/2', 'damage_desc': ['Переднее правое крыло'], 'images': 'a53404f8-3303-4b2e-9be3-1b2f036a3918'}, {'accident_id': '610004065', 'date': '19.02.2015 10:05', 'incedent_type': 'Столкновение', 'region': 'Рязанская область', 'incedent_place': 'Рязанская область, Рязань, Советский', 'venhicle_model': 'KIA(Spectra)', 'model_product_year': 'нет данных', 'opf': 'ФИЗИЧЕСКИЕ ЛИЦА', 'tc_number': '1/2', 'damage_desc': [], 'images': 'b9f2342d-270c-4dda-adf6-1b3499e4a8d3'}]}}, 'uuid': '9fcbee18-c506-4b49-9af9-0ae9bd0fbd89'}) WORKER_UUID=UUID('4f6d70d2-13e9-4f0c-8f95-863f7b677d34')
2022-02-17 12:14:13.715 | INFO     | __main__:on_request:97 -  [Server] cleaned page! WORKER_UUID=UUID('4f6d70d2-13e9-4f0c-8f95-863f7b677d34')
2022-02-17 12:23:44.371 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('4c6e7cb6-3168-4cfb-a3d6-e68a0527d9fa')
2022-02-17 12:23:44.371 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('4f6d70d2-13e9-4f0c-8f95-863f7b677d34')
2022-02-17 12:23:54.370 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:23:54.370471
2022-02-17 12:23:54.370 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('6e4daef5-79cd-497f-8e78-de09b8ee351a')
2022-02-17 12:23:54.380 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:23:54.380044
2022-02-17 12:23:54.380 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('37895e94-7ddc-47da-b837-ac91addcec94')
2022-02-17 12:24:01.191 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('6e4daef5-79cd-497f-8e78-de09b8ee351a')
2022-02-17 12:24:02.152 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('37895e94-7ddc-47da-b837-ac91addcec94')
2022-02-17 12:24:26.178 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('37895e94-7ddc-47da-b837-ac91addcec94')
2022-02-17 12:24:26.178 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('6e4daef5-79cd-497f-8e78-de09b8ee351a')
2022-02-17 12:24:29.537 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:24:29.537145
2022-02-17 12:24:29.537 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:24:29.537175
2022-02-17 12:24:29.537 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('78630169-0fb7-4098-970b-9a2e93d35c7f')
2022-02-17 12:24:29.537 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('f69279db-975e-450b-8727-8598e9877d26')
2022-02-17 12:24:37.373 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('f69279db-975e-450b-8727-8598e9877d26')
2022-02-17 12:24:37.716 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('78630169-0fb7-4098-970b-9a2e93d35c7f')
2022-02-17 12:24:55.152 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "9d6b133e-eb57-417e-97d4-8641f92797e8"}) WORKER_UUID=UUID('f69279db-975e-450b-8727-8598e9877d26')
2022-02-17 12:24:55.160 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:24:55.193 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:24:55.193 | INFO     | parsers:_get_road_accident_history:474 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 12:24:55.688 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:24:56.012 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:24:56.583 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 12:24:56.887 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:24:57.455 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 2
2022-02-17 12:24:57.758 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:24:58.327 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 3
2022-02-17 12:24:58.640 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:24:59.253 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 4
2022-02-17 12:24:59.565 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:00.135 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 5
2022-02-17 12:25:00.468 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:01.039 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 6
2022-02-17 12:25:01.502 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:25:01.812 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:02.428 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 7
2022-02-17 12:25:02.739 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:03.349 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 8
2022-02-17 12:25:03.649 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:04.260 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 9
2022-02-17 12:25:04.561 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:05.128 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 10
2022-02-17 12:25:05.444 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:06.013 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 11
2022-02-17 12:25:06.317 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:06.884 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 12
2022-02-17 12:25:07.342 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:25:07.658 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:08.225 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 13
2022-02-17 12:25:08.540 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:09.108 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 14
2022-02-17 12:25:09.437 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:10.009 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 15
2022-02-17 12:25:10.321 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:10.944 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 16
2022-02-17 12:25:11.252 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:11.822 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 17
2022-02-17 12:25:12.144 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:12.752 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 18
2022-02-17 12:25:13.211 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:25:13.525 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:14.093 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 19
2022-02-17 12:25:14.394 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:14.974 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 20
2022-02-17 12:25:15.274 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:15.843 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 21
2022-02-17 12:25:16.145 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:16.713 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 22
2022-02-17 12:25:17.023 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:17.591 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 23
2022-02-17 12:25:17.912 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:18.495 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 24
2022-02-17 12:25:18.965 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:25:19.290 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:19.900 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 25
2022-02-17 12:25:20.227 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:20.798 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 26
2022-02-17 12:25:21.335 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:22.001 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 27
2022-02-17 12:25:22.301 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:22.870 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 28
2022-02-17 12:25:23.193 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:23.765 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 29
2022-02-17 12:25:24.094 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:24.677 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 30
2022-02-17 12:25:25.140 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:25:25.467 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:26.036 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 31
2022-02-17 12:25:26.333 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:26.940 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 32
2022-02-17 12:25:27.258 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:27.825 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 33
2022-02-17 12:25:28.158 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:28.731 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 34
2022-02-17 12:25:29.066 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:29.637 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 35
2022-02-17 12:25:29.955 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:30.564 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 36
2022-02-17 12:25:31.038 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:25:31.363 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:31.955 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 37
2022-02-17 12:25:32.275 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:32.854 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 38
2022-02-17 12:25:33.160 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:25:33.742 | INFO     | parsers:_get_road_accident_history:522 - [ACCIDENT-DATA] Элемент не найден, итерация: 39
2022-02-17 12:25:33.742 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('f69279db-975e-450b-8727-8598e9877d26')
2022-02-17 12:25:33.742 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('78630169-0fb7-4098-970b-9a2e93d35c7f')
2022-02-17 12:32:19.047 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:32:19.047861
2022-02-17 12:32:19.048 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('5f5d211e-4e68-4775-9799-8d000d999fde')
2022-02-17 12:32:19.057 | INFO     | __main__:<module>:13 - [INIT] Cтарт 2022-02-17 12:32:19.057044
2022-02-17 12:32:19.057 | INFO     | __main__:<module>:16 - [INIT] Начало инициализации кролика и парсера WORKER_UUID=UUID('e378d403-ebde-4697-83a9-1be7b04153f6')
2022-02-17 12:32:25.430 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('e378d403-ebde-4697-83a9-1be7b04153f6')
2022-02-17 12:32:25.430 | INFO     | __main__:on_request:72 -  [OR] body({"vin_code": "XWKFB227390094336", "method": "road_accident_history", "uuid": "9d6b133e-eb57-417e-97d4-8641f92797e8"}) WORKER_UUID=UUID('e378d403-ebde-4697-83a9-1be7b04153f6')
2022-02-17 12:32:25.431 | INFO     | parsers:_send_field_waits:158 - Отправка кода в input_field 
2022-02-17 12:32:25.478 | INFO     | __main__:<module>:102 - [Server] Awaiting RPC requests WORKER_UUID=UUID('5f5d211e-4e68-4775-9799-8d000d999fde')
2022-02-17 12:32:25.490 | INFO     | parsers:_send_field_waits:167 - Ввод VIN кода: XWKFB227390094336
2022-02-17 12:32:25.490 | INFO     | parsers:_get_road_accident_history:474 - [ACCIDENT]Старт получения данных о ДТП
2022-02-17 12:32:26.051 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:32:26.404 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:26.914 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 1
2022-02-17 12:32:27.255 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:27.765 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 2
2022-02-17 12:32:28.082 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:28.592 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 3
2022-02-17 12:32:28.933 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:29.442 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 4
2022-02-17 12:32:29.808 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:30.328 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 5
2022-02-17 12:32:30.711 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:31.226 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 6
2022-02-17 12:32:31.741 | INFO     | parsers:_get_road_accident_history:492 - [ACCIDENT-BUTTON]Кнопка нажата
2022-02-17 12:32:42.751 | INFO     | parsers:_get_road_accident_history:501 - [ACCIDENT-DATA] Поднятие ошибки NoSuchElementException
2022-02-17 12:32:43.271 | INFO     | parsers:_get_road_accident_history:521 - [ACCIDENT-DATA] Элемент не найден, итерация: 7
2022-02-17 12:32:46.174 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:32:46.174 | INFO     | parsers:_save_road_accident_image_1c:197 - [ACCIDENT-I] Отправка изображения в сервис http://192.168.0.7/filesprogr/index.php?operation=write&extension=png&author=parserGIBDD&typedoc=2&filename=2022-02-1712:32:46.174647.jpg
2022-02-17 12:32:46.215 | INFO     | parsers:_save_road_accident_image_1c:207 - [ACCIDENT-I] UUID изображения на сервисе a53404f8-3303-4b2e-9be3-1b2f036a3918
2022-02-17 12:32:46.313 | INFO     | parsers:_save_road_accident_image_1c:194 - [ACCIDENT-I] Получение изображений ДТП
2022-02-17 12:32:46.313 | INFO     | parsers:_save_road_accident_image_1c:197 - [ACCIDENT-I] Отправка изображения в сервис http://192.168.0.7/filesprogr/index.php?operation=write&extension=png&author=parserGIBDD&typedoc=2&filename=2022-02-1712:32:46.313569.jpg
2022-02-17 12:32:46.339 | INFO     | parsers:_save_road_accident_image_1c:207 - [ACCIDENT-I] UUID изображения на сервисе b9f2342d-270c-4dda-adf6-1b3499e4a8d3
2022-02-17 12:32:46.441 | INFO     | __main__:on_request:95 -  [Server] response({'result': 'Success', 'data': {'road_accident_history': {'dtp_list': [{'accident_id': '030059033', 'date': '08.08.2018 07:45', 'incedent_type': 'Столкновение', 'region': 'Краснодарский край', 'incedent_place': 'Краснодарский край, Анапский район, Анапа', 'venhicle_model': 'KIA(Spectra)', 'model_product_year': '2008', 'opf': 'ФИЗИЧЕСКИЕ ЛИЦА', 'tc_number': '2/2', 'damage_desc': ['Переднее правое крыло'], 'images': 'a53404f8-3303-4b2e-9be3-1b2f036a3918'}, {'accident_id': '610004065', 'date': '19.02.2015 10:05', 'incedent_type': 'Столкновение', 'region': 'Рязанская область', 'incedent_place': 'Рязанская область, Рязань, Советский', 'venhicle_model': 'KIA(Spectra)', 'model_product_year': 'нет данных', 'opf': 'ФИЗИЧЕСКИЕ ЛИЦА', 'tc_number': '1/2', 'damage_desc': [], 'images': 'b9f2342d-270c-4dda-adf6-1b3499e4a8d3'}]}}, 'uuid': '9d6b133e-eb57-417e-97d4-8641f92797e8'}) WORKER_UUID=UUID('e378d403-ebde-4697-83a9-1be7b04153f6')
2022-02-17 12:32:46.975 | INFO     | __main__:on_request:97 -  [Server] cleaned page! WORKER_UUID=UUID('e378d403-ebde-4697-83a9-1be7b04153f6')
2022-02-17 12:33:19.015 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('e378d403-ebde-4697-83a9-1be7b04153f6')
2022-02-17 12:33:19.015 | INFO     | __main__:exit_gracefully:35 - [EXIT] Kill WORKER_UUID=UUID('5f5d211e-4e68-4775-9799-8d000d999fde')
